export default function Required() {
  const requiredFields = [
    "Business Name",
    "Business Type",
    "Business Address",
    "Business Activity",
    "Current Location Period",
    "Current Business Period",
    "Business TIN Number",
    "Requested Loan Amount",
    "Suggested Monthly Loan Return",
    "Loan Purpose",
    "Investment Plan",
    "FI Loan",
    "Discovered through",
    "Applicant First Name",
    "Applicant Middle Name",
    "Applicant Last Name",
    "Applicant Date of Birth",
    "Applicant ID Type",
    "Applicant ID Number",
    "Applicant Gender",
    "Applicant BVN",
    "Applicant First Telephone Number",
    "Applicant Second Telephone Number",
    "Applicant Marital Status",
    "Applicant State of Residence",
    "Applicant LGA of Residence",
    "Applicant Signature Date",
    "Applicant Signature",
    "Applicant's Spouse's First Name",
    "Applicant's Spouse's Middle Name",
    "Applicant's Spouse's Last Name",
    "Applicant's Spouse's Date of Birth",
    "Applicant's Spouse's First Telephone Number",
    "Applicant's Spouse's Second Telephone Number",
    "Next of Kin's Name",
    "Next of Kin Gender",
    "Next of Kin's Relationship with Applicant",
    "Next of Kin's Telephone Number",
  ];

  return { requiredFields };
}
